version: '3.8'

services:
  inventory-service:
    build: .
    container_name: inventory-service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
